# Generated by Django 4.1.2 on 2022-11-05 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0002_calcdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalcData',
        ),
    ]
